### ISSUE TITLE
PolyGen vs Polygen

### ISSUE THREAD

**Issue by alvisespano** [tajmone/polygen-grammars#1]
Nei README che scrissi all'epoca battezzai PolyGen (con anche G maiuscola) il programma, ma in molti altri documenti successivi e sopratutto nella quotidiana informalità, tutti - io incluso - l'abbiamo sempre chiamato Polygen (con la g minuscola).
Secondo me aboliamo la notazoine PolyGen e scriviamo sempre e solo, ovunque, Polygen, che mi sembra meno pesante e più familiare.

**Comment by tajmone** [comment]
Sì, questa cosa l'avevo notata.

Ok, mi pianifico per bene una mega operazione di search and replace nei vari repository (che includono anche i Wiki) e man mano che li ho completati aggiorno questo post.

### Repo da Modificare

-  [x] Polygen
    +  [x] alvisespano/Polygen.wiki
    +  [x] tajmone/Polygen.wiki
-  [x] polygen-docs
-  [x] polygen-grammars

**Comment by tajmone** [comment]
Nel progetto dei documenti ho corretto tutte le occorrenze di PolyGen in Polygen, tranne nelle macro PP e nelle sintassi Highlight (e riferimenti ad essa) dato che quello è ormai lo spelling con cui la definizione della sintassi è sata incorporata nel progetto Highlight.

I file dei documenti html originali per ora li ho lasciati col vecchio nome.

**Comment by tajmone** [comment]
Tutto sommato, preferivo "PolyGen", per due ragioni.

La prima, forse più banale, è che una ricerca Google rivela che esistono già svariati programmi e librerie chiamati "Polygen", molti meno chiamai "PolyGen".

La seconda, indubbiamente più ludica, è che trovo che il termine "PolyGen" si presti naturalmente a giochi di parole. Basti pensare solo all'applicativo "PolyGUI", che è immediatamente associabile a "PolyGen" in quanto parola (apparentemente) composta.

L'illusione che PolyGen sia composto da due parti lascia spazio all'immaginazione. Per fare un esempio (assurdo):

> La nuova interfaccia PolyGenio è l'ultima frontiera per la PolyGentaglia di questa PolyGenerazione di PolySfi**ti.

E in inglese risulterebbe ancora più facile creare giochi d'assonanza e di rimando:

> "PolyGender" is the latest politically-incorrect PolyGrammar published. Then comes "PolyJokes", and finally the "PolyTrinity" (includes three modules: "PolyFather", "PolySon" and "PolySpirit"). What can I say, but "PolySh*t"!

E via dicendo. Quella "G" maiuscola, in qualche modo semplificava creare termini quali "PolyGrammar" (che suona meglio di "Polygen Grammar").

**Comment by alvisespano** [comment]
A me lo dici? Sono io che ho fatto la grammatica che storpia il nome in
Folpygel e quelle minchiate là.
Ma la grafia di PolyGen è pesante e nessuno la usa, quindi tanto vale che
lo chiamiamo Polygen tutti anche nei documenti.



Il giorno 18 gennaio 2018 12:29, Tristano Ajmone <notifications@github.com>
ha scritto:

**Comment by alvisespano** [comment]
Cioè, mi spiego meglio: trovo che la *grafia* con la G maiuscola sia un po'
antiquata e meno "fluida" di Polygen, non so come spiegarmi :P

Il giorno 18 gennaio 2018 14:53, Alvise Spanò <spano.alvise@gmail.com> ha
scritto:

**Comment by tajmone** [comment]
> Ma la grafia di PolyGen è pesante e nessuno la usa, quindi tanto vale che
lo chiamiamo Polygen tutti anche nei documenti.

L'importante è definire una grafia ufficiale, a scanso di equivoci — tanto a violarla nell'uso pratico ci penseranno gli utenti!

> Cioè, mi spiego meglio: trovo che la *grafia* con la G maiuscola sia un po'
antiquata e meno "fluida" di Polygen, non so come spiegarmi :P

In effetti il rischio è che poi venga abbreviato in "PG", mentre è invece una parola sola.

Io sono un po' fissato con la modifica dei nomi di applicazioni e servizi in forme a me più gradite. Per esempio, nei miei file (link, documenti, ecc.) scrivo sempre "WikiPedia" anziché "Wikipedia" (è sbagliato, lo so, è come scrivere "EncicloPedia", ma l'estetica della storpiatura non conosce ragioni). In parte è una fissa nata dal fatto che semplifica individuare i file tra lunghe liste con caratteri minuscoli, il resto è mero piacere storpiante.

**Comment by tajmone** [comment]
Bene, ho finito di modificare lo spelling in TUTTI i progetti (vedi sopra), incluse le sintassi di Higlight.

Le uniche cose che non ho cambiato sono le grammatiche scritte da altri. Per il resto, direi che ora abbiamo ufficialmente spazzato via il vecchio nome.

**Comment by alvisespano** [comment]
Grande! :)

Il giorno 19 gennaio 2018 00:04, Tristano Ajmone <notifications@github.com>
ha scritto:
